### ISSUE TITLE
CT: should not be called if disposed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#133]
Also in Graphing Slope Intercept
```
graphing-lines : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603956297510%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM

----------------------------------

graphing-lines : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603968342803%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM

----------------------------------

graphing-lines : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603975592760%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM

----------------------------------

graphing-lines : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603959842414%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM

----------------------------------

graphing-lines : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603968307846%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM

----------------------------------

graphing-lines : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/graphing-lines_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-lines%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1603955212806%22%2C%22timestamp%22%3A1603982478720%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/assert/js/assert.js:22:13)
at TinyForwardingProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:53:15)
at TinyForwardingProperty.notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:167:10)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyProperty.js:70:12)
at TinyForwardingProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyForwardingProperty.js:151:13)
at GraphPointSlopeNode.setPickable (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3386:28)
at GraphPointSlopeNode.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/scenery/js/nodes/Node.js:3390:32)
at playStateObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/graphing-lines/js/linegame/view/GraphTheLineNode.js:136:31)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/TinyEmitter.js:85:42)
at EnumerationProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603955212806/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 10/29/2020, 1:06:52 AM
```

**Comment by pixelzoom** [comment]
This appears to be related to `pickableProperty` -- `GraphPointSlopeNode.setPickable`. It started occurring 10/28/2020 at 4:00PM.  It occurs on most (but not all) CT cycles.  

@samreid and @zepumph have been working on pickableProperty. Any ideas?

**Comment by pixelzoom** [comment]
Reproduced in master by running graphing-slope-intercept from phetmarks with ?fuzz.  The sim fails immediately on startup.  

Here's the relevant code sequence in GraphTheLineNode constructor. Failure occurs on lien 136. 

```js
    // sync with game state
    const playStateObserver = playState => {

      // states in which the graph is interactive
136   this.graphNode.pickable = ...
    };
    model.playStateProperty.link( playStateObserver ); // unlink in dispose

    // @private called by dispose
    this.disposeGraphTheLineNode = () => {
      ...
      model.playStateProperty.unlink( playStateObserver );
      ...
      this.graphNode.dispose();
    };
```

Note that in `disposeGraphTheLineNode`, playStateObserver is unlinked before graphNode is disposed.  So I'm wondering if Node is not properly disposing of pickableProperty.

**Comment by pixelzoom** [comment]
I added this line to the beginning of `playStateObserver`:

```js
      assert && assert( !this.graphNode.isDisposed, 'graphNode is disposed' );
```

... and the assertion fails.  So this looks like a sim-specific problem.

**Comment by zepumph** [comment]
The issue is because we began disposing visible and pickable Properties in Node on dispose (like in https://github.com/phetsims/scenery/commit/f4097d022dcc34abdc748841c1b1534fd126244a). 

Before that, this was still a sim-specific problem, as pickable listeners were being called after Node disposal, it's just that the pickableProperty wasn't actually getting disposed.

This is similar to the sim-specific issue @samreid and I looked into over in https://github.com/phetsims/energy-forms-and-changes/issues/399

**Comment by pixelzoom** [comment]
If I comment out this line in GraphTheLineNode:

```js
 this.graphNode.dispose();
```

... then I get a similar failure for visibleProperty in ChallengeNode line 118:

```js
  setGuessLineVisible( visible ) {
118 this.guessLineNode.visible = visible;
  }
```

Here's the stack trace:

```
assert.js:22 Uncaught Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (assert.js:22)
    at TinyForwardingProperty.emit (TinyEmitter.js:53)
    at TinyForwardingProperty.notifyListeners (TinyForwardingProperty.js:167)
    at TinyForwardingProperty.set (TinyProperty.js:70)
    at TinyForwardingProperty.set (TinyForwardingProperty.js:151)
    at LineNode.setVisible (Node.js:3209)
    at LineNode.set visible [as visible] (Node.js:3213)
    at ChallengeGraphNode.setGuessLineVisible (ChallengeGraphNode.js:118)
    at playStateObserver (MakeTheEquationNode.js:124)
    at TinyEmitter.emit (TinyEmitter.js:85)
```

Again, order of disposal looks correct -- listeners are removed before disposing Nodes that are used by listeners -- so I'm not sure why this is occurring.

**Comment by zepumph** [comment]
In the EFAC issue (converted into this case), was the following:

Note that the pickability is being changed from this listener:

https://github.com/phetsims/graphing-lines/blob/bb134df9021fa4a7e9e0bd2c86bfe7ad66857464/js/linegame/view/MakeTheEquationNode.js#L137

based on `model.playStateProperty`

If there is an earlier listener attached to playStateProperty that is responsible for disposing the graphNode, Then TinyEmitter (responsible for Property listener notification) will make a defensive copy of the listener list, and even though the graphNode is disposed, and the listener to the playStateProperty has been removed, it will still be called as part of that playState change.

Specific for this case, it looks like the following thing stack:

* This link https://github.com/phetsims/graphing-lines/blob/541744d16fb81dc1224f3105425ec2424844746b/js/linegame/model/BaseGameModel.js#L87 will change the challengeProperty.
* Which will result in https://github.com/phetsims/graphing-lines/blob/dbed99ec52a8d539ed69d42f0d88ee43eedfe462/js/linegame/view/PlayNode.js#L75 disposing the graphNode
* Then later on in the listener list of the `playStateProperty` the listener to change graphNode pickability will change.

In EFAC, we could not think of an easy way of fixing this well save changing the pattern of listeners in general. Thus we just guarded around disposal, instead of asserting that it wasn't disposed. We aren't very happy about that, but we the problem. Let me know what you would like to do!

**Comment by pixelzoom** [comment]
Thanks for the explanation @zepumph, that is also what is happening in this case.   I've addressed this in the above commit in the same way that you did for EFAC -- playStateObserver is now a no-op if the challenge Node has been disposed.

I'll leave this open until CT indicates all clear.

**Comment by pixelzoom** [comment]
CT has been clear for 2 cycles. Closing.
