### ISSUE TITLE
CT Missing string information for graphing-lines symbo

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-lines#141]
Also in slope-intercept
```
graphing-lines : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 22452ms
Building runnable repository (graphing-lines, brands: phet)
Building brand: phet
>> Webpack build complete: 5288ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for graphing-lines symbo
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/getStringMap.js:225:11
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/getStringMap.js:213:15
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/getStringMap.js:212:23
at Array.forEach (<anonymous>)
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/getStringMap.js:149:24)
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/buildRunnable.js:143:41)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/Gruntfile.js:298:15
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/Gruntfile.js:297:13
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/Gruntfile.js:225:7
at async wrap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1690476738819/chipper/js/grunt/Gruntfile.js:69:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Missing string information for graphing-lines symbo
Snapshot from 7/27/2023, 10:52:18 AM
```

**Comment by pixelzoom** [comment]
Bisecting tells me that this was introduced yesterday 7/27/23 at 11:59AM.  To confirm:

> % cd graphing-lines
% git checkout 9798865 
% grunt

**Comment by pixelzoom** [comment]
This failure was caused by a code comment, which is really odd, and reported in https://github.com/phetsims/chipper/issues/1401.   In the meantime, I've changed the comment to prevent the failure.
